// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_consolescreen = NULL;lv_obj_t *ui_Container1 = NULL;
lv_obj_t * log_list;
lv_obj_t * log_items[30];
// event funtions

// build funtions

void ui_consolescreen_screen_init(void)
{
ui_consolescreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_consolescreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_consolescreen, lv_color_hex(0x001F1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_consolescreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

log_list = lv_list_create(ui_consolescreen);
lv_obj_set_size( log_list, lv_pct(100), lv_pct(100));
lv_obj_align(log_list, LV_ALIGN_TOP_LEFT, 0, 0);
lv_obj_set_scrollbar_mode(log_list, LV_SCROLLBAR_MODE_AUTO);
lv_obj_set_scroll_dir(log_list, LV_DIR_VER);
lv_obj_set_scroll_snap_x(log_list, LV_SCROLL_SNAP_END);
lv_obj_set_style_text_color(log_list, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(log_list, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(log_list, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(log_list, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_pad_all(log_list, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_consolescreen_screen_destroy(void)
{
   if (ui_consolescreen) lv_obj_del(ui_consolescreen);

// NULL screen variables
ui_consolescreen= NULL;
log_list= NULL;
for (uint8_t i = 0; i < 30; i++) {
    log_items[i] = NULL;
}

}
