// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_CONSOLESCREEN_H
#define UI_CONSOLESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_consolescreen
extern void ui_consolescreen_screen_init(void);
extern void ui_consolescreen_screen_destroy(void);
extern lv_obj_t *ui_consolescreen;
extern lv_obj_t *ui_Container1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

