// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_consolescreen = NULL;lv_obj_t *ui_textarea1 = NULL;
// event funtions

// build funtions

void ui_consolescreen_screen_init(void)
{
ui_consolescreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_consolescreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textarea1 = lv_textarea_create(ui_consolescreen);
lv_obj_set_width( ui_textarea1, lv_pct(100));
lv_obj_set_height( ui_textarea1, lv_pct(100));
lv_obj_set_align( ui_textarea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_textarea1,"Waiting for console data...");
lv_obj_clear_flag( ui_textarea1, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_textarea1, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_textarea1, LV_DIR_HOR);
lv_obj_set_scroll_snap_x(ui_textarea1, LV_SCROLL_SNAP_END);
lv_obj_set_style_text_color(ui_textarea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textarea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_textarea1, lv_color_hex(0x002322), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_textarea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_textarea1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textarea1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

}

void ui_consolescreen_screen_destroy(void)
{
   if (ui_consolescreen) lv_obj_del(ui_consolescreen);

// NULL screen variables
ui_consolescreen= NULL;
ui_textarea1= NULL;

}
