// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_keyboardscreen = NULL;
// event funtions

// build funtions

void ui_keyboardscreen_screen_init(void)
{
ui_keyboardscreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_keyboardscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_keyboardscreen, lv_color_hex(0x00101D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_keyboardscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_keyboardscreen_screen_destroy(void)
{
   if (ui_keyboardscreen) lv_obj_del(ui_keyboardscreen);

// NULL screen variables
ui_keyboardscreen= NULL;

}
