// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_midicontrolscreen = NULL;
// event funtions

// build funtions

void ui_midicontrolscreen_screen_init(void)
{
ui_midicontrolscreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_midicontrolscreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_midicontrolscreen, lv_color_hex(0x1F1200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_midicontrolscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_midicontrolscreen_screen_destroy(void)
{
   if (ui_midicontrolscreen) lv_obj_del(ui_midicontrolscreen);

// NULL screen variables
ui_midicontrolscreen= NULL;

}
