// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainscreen
extern void ui_mainscreen_screen_init(void);
extern void ui_mainscreen_screen_destroy(void);
extern lv_obj_t *ui_mainscreen;
extern void ui_event_button1( lv_event_t * e);
extern lv_obj_t *ui_button1;
extern lv_obj_t *ui_button2;
extern lv_obj_t *ui_label1;
extern lv_obj_t *ui_value;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

