// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_MIDICONTROLSCREEN_H
#define UI_MIDICONTROLSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_midicontrolscreen
extern void ui_midicontrolscreen_screen_init(void);
extern void ui_midicontrolscreen_screen_destroy(void);
extern lv_obj_t *ui_midicontrolscreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

