// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_mainscreen = NULL;lv_obj_t *ui_button1 = NULL;lv_obj_t *ui_button2 = NULL;lv_obj_t *ui_label1 = NULL;lv_obj_t *ui_value = NULL;
// event funtions
void ui_event_button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_consolescreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_consolescreen_screen_init);
      ( e );
}
}

// build funtions

void ui_mainscreen_screen_init(void)
{
ui_mainscreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mainscreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_mainscreen, lv_color_hex(0x3B7A4A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_mainscreen, lv_color_hex(0x3A7B7A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_mainscreen, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_mainscreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_button1 = lv_btn_create(ui_mainscreen);
lv_obj_set_width( ui_button1, 60);
lv_obj_set_height( ui_button1, 60);
lv_obj_set_x( ui_button1, 30 );
lv_obj_set_y( ui_button1, 30 );
lv_obj_add_state( ui_button1, LV_STATE_PRESSED );     /// States
lv_obj_add_flag( ui_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_button1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_button1, lv_color_hex(0xFFDF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_button1, lv_color_hex(0xFFF088), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_button1, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_button2 = lv_btn_create(ui_mainscreen);
lv_obj_set_width( ui_button2, 60);
lv_obj_set_height( ui_button2, 60);
lv_obj_set_x( ui_button2, -30 );
lv_obj_set_y( ui_button2, 30 );
lv_obj_set_align( ui_button2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label1 = lv_label_create(ui_mainscreen);
lv_obj_set_width( ui_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_label1, -127 );
lv_obj_set_x( ui_label1, lv_pct(-23) );
lv_obj_set_align( ui_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_label1,"Uart\nTerminal");
lv_obj_set_style_text_color(ui_label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_value = lv_label_create(ui_mainscreen);
lv_obj_set_width( ui_value, 197);
lv_obj_set_height( ui_value, 17);
lv_obj_set_align( ui_value, LV_ALIGN_CENTER );
lv_label_set_recolor(ui_value,"true");
lv_obj_set_style_text_align(ui_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_button1, ui_event_button1, LV_EVENT_ALL, NULL);

}

void ui_mainscreen_screen_destroy(void)
{
   if (ui_mainscreen) lv_obj_del(ui_mainscreen);

// NULL screen variables
ui_mainscreen= NULL;
ui_button1= NULL;
ui_button2= NULL;
ui_label1= NULL;
ui_value= NULL;

}
