// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_consolescreen = NULL;
// event funtions

// build funtions

void ui_consolescreen_screen_init(void)
{
ui_consolescreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_consolescreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_consolescreen, lv_color_hex(0x001F1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_consolescreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_consolescreen_screen_destroy(void)
{
   if (ui_consolescreen) lv_obj_del(ui_consolescreen);

// NULL screen variables
ui_consolescreen= NULL;

}
