// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_mainscreen = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Button2 = NULL;
// event funtions
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_consolescreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_consolescreen_screen_init);
}
}

// build funtions

void ui_mainscreen_screen_init(void)
{
ui_mainscreen = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_mainscreen, lv_color_hex(0x16302B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainscreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_mainscreen);
lv_obj_set_width( ui_Button1, 120);
lv_obj_set_height( ui_Button1, 120);
lv_obj_set_x( ui_Button1, 0 );
lv_obj_set_y( ui_Button1, -156 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFF26B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_mainscreen);
lv_obj_set_width( ui_Button2, 120);
lv_obj_set_height( ui_Button2, 120);
lv_obj_set_x( ui_Button2, 0 );
lv_obj_set_y( ui_Button2, 3 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_mainscreen_screen_destroy(void)
{
   if (ui_mainscreen) lv_obj_del(ui_mainscreen);

// NULL screen variables
ui_mainscreen= NULL;
ui_Button1= NULL;
ui_Button2= NULL;

}
